# Generated by Django 5.1.6 on 2025-05-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, null=True, verbose_name="Имя пользователя"
            ),
        ),
    ]
