# Generated by Django 5.1.6 on 2025-04-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date_payment",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата оплаты"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="total_cost",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Сумма оплаты"
            ),
        ),
    ]
