[tool.poetry]
name = "pythondrfprojecthomework"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
djangorestframework-simplejwt = "^5.5.0"
djangorestframework = "^3.16.0"
setuptools = "^80.3.1"
dotenv = "^0.9.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
