# Generated by Django 5.1.6 on 2025-05-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["name"],
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="video_url",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="ссылка на видео-материал",
            ),
        ),
    ]
