# Generated by Django 5.1.6 on 2025-05-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_alter_lesson_options_course_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="video_url",
            field=models.CharField(
                blank=True, null=True, verbose_name="ссылка на видео-материал"
            ),
        ),
    ]
