# Generated by Django 5.1.6 on 2025-05-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_alter_course_video_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="video_url",
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.CharField(
                blank=True, null=True, verbose_name="ссылка на видео-материал"
            ),
        ),
    ]
