# Generated by Django 5.2.1 on 2025-05-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_remove_course_video_url_lesson_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновление курса"),
        ),
    ]
